version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build: ./server
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shareit
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    ports:
      - "9090:9090"

  gateway:
    build: ./gateway
    depends_on:
      - server
    environment:
      SHAREIT_SERVER_URL: http://server:9090
    ports:
      - "8080:8080"

volumes:
  db_data:
